apiVersion: apps/v1
kind: Deployment
metadata:
  name: league-of-locals-admin-panel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: league-of-locals-admin-panel
  template:
    metadata:
      labels:
        app: league-of-locals-admin-panel
    spec:
      containers:
      - name: league-of-locals-admin-panel
        image: ghcr.io/leagueoflocalsdev/league-of-locals-admin-panel:latest
        ports:
        - containerPort: 3000
        env:
          - name: APP_BASE_URL
            value: "https://admin.leagueoflocals.xyz"
          - name: NEXT_PUBLIC_BASE_PATH
            value: "/admin"
          - name: USER_API_BASE_URL
            value: "http://league-of-locals-user-api-svc:80"
          - name: AUTH0_AUDIENCE
            value: "https://api.leagueoflocals.xyz"
          - name: AUTH0_SCOPE
            value: "openid profile email"
        envFrom:
          - secretRef:
              name: admin-panel-auth0-secrets
      imagePullSecrets:
      - name: ghcr-secret
